server:
  port: "8011"

database:
  active: "mongodb" # or "mongodb"
  mongodb:
    host: "mongo-main"
    port: "27017"
    # user: "Senbox"
    # password: ""
    name: "media_service_db"

  redis:
    host: "redis"
    port: "6379"
    password: "senbox"
    db: 1

  redis_cache:
    ttlSeconds: 0 #config time circle cache
    host: "redis"
    port: "6379"
    password: "senbox"
    db: 10

consul:
    host: "consul"
    port: 8500
    
registry:
  host: 192.0.2.60

s3:   
  senbox-form-submit-bucket:    
   domain: 'https://d2tlyqjp4runby.cloudfront.net'     
   region: 'ap-southeast-1'     
   bucket_name: 'senbox-form-submit-bucket'     
   access_key: 'AKIA2HVQ5GUIDTHLCKP3'     
   secret_key: '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'     
   cloudfront_key_group_id: 'K1RAOUJU1Q3EVC'     
   cloudfront_key_path: '/keys/senbox-form-submit-bucket/private_key.pem'

